import Hero from "@/components/Hero";
import JoinUs from "@/components/JoinUs";
import Head from "next/head";


export default function Home() {
  return (
    <>
      <Head>
        <title>Coding Moon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <JoinUs />

    </>
  )
}
